--- 
output_dir: output
data_sources: 
- type: filesystem_unified
  items_root: /
  layouts_root: /

# Custom settings

# Use rsync + ssh for live site. To deploy:
#
#   % rake deploy:rsync
deploy:
  default:
    dst: "mgutz_com:www/nanoc3_blog"
    options: ['-ave ssh', '--exclude=.DS_Store', '--exclude=*~']

# domain to which this site is deployed
base_url: http://nanoc-blog-kit.mgutz.com

google_analytics:
  domain: ''
  site_id: ''

# currently used by logo
site_name: Redmine Blog - The Official Redmine blog

# number of full featured posts to display on front
featured_count: 0

# number of excerpted posts to display on front
excerpt_count: 10

# number of other articles to reference at bottom of each article
other_articles_max: 5

# DISQUS Site Shortname. Comment out to disable.
disqus_shortname: nanoc3-blog

site_url: http://redmineblog.com
site_author: Eric Davis
site_author_email: 'edavis@littlestreamsoftware.com'
paginate: 10
global_feed: 'http://feeds2.feedburner.com/RedmineBlog'
email_feed: 'http://feedburner.google.com/fb/a/mailverify?uri=RedmineBlog'
permalink: '/articles/:title'
markdown: rdiscount
pygments: true
